const recommendations=[{keywords:["beach","bora","maldives"],title:"Beach recommendation",text:"Try Bora Bora or the Maldives for a relaxing beach trip."},{keywords:["temple","kyoto","bali","japan","indonesia"],title:"Temple recommendation",text:"Consider Kyoto in Japan or Bali in Indonesia for temples and cultural experiences."},{keywords:["switzerland","swiss"],title:"Country recommendation",text:"Switzerland is a good choice for mountain scenery, scenic trains, and peaceful towns."},{keywords:["france","paris"],title:"Country recommendation",text:"France offers historic cities, famous landmarks, food, and a wide variety of places to explore."}];
const searchInput=document.getElementById("searchInput"),searchButton=document.getElementById("searchButton"),searchResults=document.getElementById("searchResults");
function performSearch(){if(!searchInput||!searchResults)return;const query=searchInput.value.trim().toLowerCase();searchResults.innerHTML="";if(!query){searchResults.innerHTML='<div class="result">Please enter a destination or category to search.</div>';return}const matches=recommendations.filter(item=>item.keywords.some(k=>k.includes(query)||query.includes(k)));if(!matches.length){searchResults.innerHTML='<div class="result">No recommendation found. Try “beach”, “temple”, “Japan”, “Switzerland”, or “France”.</div>';return}matches.forEach(item=>{const result=document.createElement("div");result.className="result";result.innerHTML=`<strong>${item.title}</strong><br>${item.text}`;searchResults.appendChild(result)})}
if(searchButton)searchButton.addEventListener("click",performSearch);
if(searchInput)searchInput.addEventListener("keydown",e=>{if(e.key==="Enter")performSearch()});
const contactForm=document.getElementById("contactForm");
if(contactForm)contactForm.addEventListener("submit",e=>{e.preventDefault();document.getElementById("formMessage").textContent="Thanks for your message! This demo form is ready for GitHub Pages.";contactForm.reset()});

const clearButton=document.getElementById("clearButton");
if(clearButton)clearButton.addEventListener("click",()=>{if(searchInput)searchInput.value="";if(searchResults)searchResults.innerHTML="";});
